### ISSUE TITLE
missing script in utils

### ISSUE THREAD

**Issue by HamedBabaei** [shengliu66/ICV#1]
Hey @shengliu66 , thanks for the nice work!

Unfortunately during the testing, I am getting the following error:
```python
      3 import torch
      4 from transformers import PreTrainedModel
----> 5 from utils.llm_layers import get_embedding_layer, get_layers, get_attention_layers, get_mlp_layers
      8 @dataclass
      9 class ResidualStream:
     10     hidden: torch.Tensor

ModuleNotFoundError: No module named 'utils.llm_layers'
```

It seems to be `llm_layers` script is missing from utils. Can you upload it as well?

**Comment by HamedBabaei** [comment]
Thanks @shengliu66 for quick reaction on the updating the repository for the missing script. However, unfortunately during the testing (after having `llm_layers` script) there is another script that is missing.

```python
     14 from utils.pca import PCA
     15 from utils.context_manager import modified_forward_context_manager, traced_forward_context_manager
---> 16 from utils.latent_shifter import LatentShifter
     17 logger = logging.getLogger("task")
     20 class BaseProbInference:

ModuleNotFoundError: No module named 'utils.latent_shifter'
```

However, I think the `LatentShifter` is not being called in the `base.py` script, which I can remove line 16 in `base.py` script to be able run the implementation. Please correct me if I am missing something here. 

Please feel free  to close the issue if there is no comment on this!

Thanks for all the work.

**Comment by shengliu66** [comment]
Thank you for pointing this out, I will update it. Thx!
