### ISSUE TITLE
Confusion regarding what kind of output is used to generate ICVs

### ISSUE THREAD

**Issue by sanchit-ahuja** [shengliu66/ICV#3]
Hi,

Thank you for your excellent work! I had a question regarding the model outputs that you are using to generate the ICVs. Are you using the output of only the attention layers or _after_ the activation layer as well? According to [this](https://github.com/shengliu66/ICV/blob/ae4fb0a2bbbb4e468053e9c357a42efda4990e18/tasks/base.py#L253), it seems like the direct output after the activation has been taken. Also, I was unable to find reference to this in the paper as well.

Thanks a lot!

**Comment by shengliu66** [comment]
Hey, thank you for asking, because of the multi-head problem, it is easier to take the activations after the fc layers, so we did this.
