### ISSUE TITLE
Getting the activations from the last-position token

### ISSUE THREAD

**Issue by yfqiu98** [shengliu66/ICV#4]
Hi there,

Thanks for your great work. I have a question regarding how you extract the last token - I see from the code that you extract the last 4 tokens and do a average pooling to get the activations rather than the last single token,

`task_latents = forward_trace.residual_stream.hidden[:, :, -4:, :].mean(2,keepdim=False) #[:, :, -1, :] # get last token`

https://github.com/shengliu66/ICV/blob/8cdce613cc5d2c44a1afecb8f8db81c4cb41c7c5/tasks/base.py#L279C46-L279C136?plain=1

Is there any mismatch with the description of the paper? And how to choose the hyperparameter that how many tokens to be used?

**Comment by icrto** [comment]
I was also wondering the same thing...

**Comment by sumingfirst** [comment]
你的邮件我受到非常感谢配合

**Comment by shengliu66** [comment]
Hi,

Thank you and sorry for the late response, we tried both the last token and the average of the last few tokens, and it worked similarly.
