### ISSUE TITLE
What's the classifier model used for the automatic evaluation of generation safety?

### ISSUE THREAD

**Issue by MaxLEAF3824** [shengliu66/ICV#5]
In section 4.1 of the paper, they talk about a Transformer classifier that has 2.7 billion parameters. Could you tell me the exact name of this classifier? Also, did you train this model from the beginning yourself, or did you use a off-the-shelf model that was already available?

**Comment by shengliu66** [comment]
We use OffensiveLanguageClassifier from parlai.
