### ISSUE TITLE
Please upload the complete task eval and model code

### ISSUE THREAD

**Issue by Yingjia-Wan** [shengliu66/ICV#7]
Hi! 

Thank you for the great work and insights in the paper. I am using your method as a baseline for a different research project, but I am facing difficulty replicating your results from just a demo_example code. Could you please upload the complete code (including the eval of different tasks for LLAMA and falcon as mentioned in the paper)?

Big appreciation!

**Comment by sumingfirst** [comment]
你的邮件我受到非常感谢配合

**Comment by pkulium** [comment]
same request here

**Comment by shengliu66** [comment]
updated! Thanks for your attention.
