### ISSUE TITLE
Missing task classes

### ISSUE THREAD

**Issue by Tobi2K** [shengliu66/ICV#9]
Hi all!
I am very interested in your paper and liked your idea. I would like to reproduce the setup you used. As far as I can see, some tasks are missing their respective classes. Could you perhaps upload the missing task classes (i.e., Shakespeare imitation, formality transfer, sentiment transfer, emotive style transfer, and formatting)?
Any additional tasks you upload would be greatly appreciated! 

Have a nice day :)

**Comment by sumingfirst** [comment]
你的邮件我受到非常感谢配合

**Comment by sumingfirst** [comment]
你的邮件我受到非常感谢配合

**Comment by Davido111200** [comment]
Hi @shengliu66, can you please update the missing classes? Thanks!
